/** Bubble page specs — a page described as plain, JSON-serialisable
    blocks. A spec can be written by hand, built by a view function from
    yazhi-api data (src/lib/foundry/views.ts), generated by an agent, or
    later served by yazhi-api itself; <BubbleView> renders all of them the
    same way. Each block's fields are exactly its component's props, so
    there is one source of truth for what a block accepts. */
import type { Tone } from "../tone";
import type { BiText } from "../core/Text";
import type { PageHeaderProps } from "../patterns/PageHeader";
import type { BubbleCardProps } from "../patterns/BubbleCard";
import type { StageSpec } from "../patterns/StageTrack";
import type { FindingSpec } from "../patterns/FindingList";
import type { KeyValueItem } from "../patterns/KeyValue";
import type { DataTableProps } from "../patterns/DataTable";

export interface StatItem {
  label: BiText;
  value: string;
  hint?: BiText;
  tone?: Tone;
}

export type Block =
  | ({ kind: "header" } & PageHeaderProps)
  | { kind: "notice"; tone?: Tone; badge?: string; title: string; body?: string }
  | { kind: "stats"; items: StatItem[] }
  | { kind: "cards"; columns?: 2 | 3; items: BubbleCardProps[] }
  | { kind: "stages"; label?: string; stages: StageSpec[] }
  | { kind: "findings"; items: FindingSpec[]; empty?: string }
  | { kind: "keyvalue"; items: KeyValueItem[] }
  | ({ kind: "table" } & DataTableProps)
  | { kind: "empty"; title: BiText; body?: BiText; art?: "sleepy" | "thinking" | "surprised" }
  | { kind: "text"; body: BiText }
  | {
      kind: "section";
      title: BiText;
      description?: BiText;
      tone?: Tone;
      /** wrap children in a single bubble (true) or lay them out bare */
      framed?: boolean;
      blocks: Block[];
    };

export type BlockKind = Block["kind"];

export interface PageSpec {
  blocks: Block[];
}
